repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
    - repo: local
      hooks:
          - id: cargo-fmt
            name: Rust Formatter
            description: "A tool for formatting Rust code according to style guidelines."
            language: rust
            entry: rustfmt
            types: [rust]
